services:
  fastapi:
    image: fastapi:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  streamlit:
    image: streamlit:dev
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    ports:
      - 8051:8051
    environment:
      API_URL: http://fastapi:8080